version: "3.9"
services:
 db:
  image: mysql
  ports:
   - 3306
  volumes:
   - myvolume:/var/lib/sql
  networks:
   - mynet
  environment:
   - MYSQL_ROOT_PASSWORD=Satara@123
   - MYSQL_DATABASE=wordpressdb

 wordpress:
  image: wordpress
  ports:
   - 80:80
  networks:
   - mynet
  environment:
   - WORDPRESS_DB_HOST=db
   - WORDPRESS_DB_USER=root
   - WORDPRESS_DB_PASSWORD=Satara@123
   - WORDPRESS_DB_NAME=wordpressdb

networks:
 mynet:
  driver: bridge
volumes:
 myvolume:


